[package]
name = "rust-os-doccumented"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "rust-os-doccumented"
test = false
bench = false
[dependencies]
